### ISSUE TITLE
Propose ListCodec.command

### ISSUE THREAD

**Issue by cecekpawon** [Mirone/AppleHDAPatcher#1]
Hello, great job as usual! This time i would like to propose some code change for this file..

[#ln](https://github.com/Mirone/AppleHDAPatcher/blob/master/AppleHDAPatcher.app/Contents/Resources/ListCodec.command#L17): We need **codec-id** & not **pci-id**, which affect procedure below

[#ln](https://github.com/Mirone/AppleHDAPatcher/blob/master/AppleHDAPatcher.app/Contents/Resources/ListCodec.command#L95): In my case i have GTX650 HDMI (GK107: **0x10de0e1b** with codec-id: **0x10de0042**)  always detected as "**Unknown**", do you think  this filters is actually useless?

So here is my propose:
- All codec vars insert into global array (HDMI table grabbed from Linux)
- Sorted by codec-id, all in lowercase for easy case sensitive parse & update
- Single loop procedure to detect all available codecs

Please take a look my revision: https://gist.github.com/cecekpawon/a76c7ae069d5c8aeb7fc

**Comment by Mirone** [comment]
Thanks, it´s done!!
