### ISSUE TITLE
Changing layout-id from 3 to 13

### ISSUE THREAD

**Issue by mgraham** [Mirone/AppleHDAPatcher#10]
I'm using one of the Realtek ALC 269 VC codecs.  I haven't had any luck with the clover plist + DSDT approach or with the patched AppleHDA approach.  

My understanding is that for my laptop, I'm supposed to use layout 13, not layout 3.  I wonder if that is the problem?  Is there any way to change layout 3 to layout 13?

(I'm using 10.11.6 on a thinkpad x230)

**Comment by Mirone** [comment]
Why do you think the problem is Layout ID? Sorry for the delay in replying but now I do not have much time for Hackintosh stuff.
P.S: Let me know if your problem has been resolved.

**Comment by mgraham** [comment]
Sorry - that was a misunderstanding on my part - I was just guessing about the Layout ID - I thought it was specific to the hardware not to the driver.

I did manage to get audio working in the end using another method:  https://github.com/Bizzaro/x230-osx/issues/4

Thanks for your help!
