### ISSUE TITLE
No "IDT 92HD93BXX"

### ISSUE THREAD

**Issue by Niller303** [Mirone/AppleHDAPatcher#12]
Can this audio device be added for laptop?

I have attached my codec dump of it.
[codec.txt](https://github.com/Mirone/AppleHDAPatcher/files/1269304/codec.txt)

**Comment by Mirone** [comment]
I'm sorry for taking time to respond,
but at the moment I'm without a hackintosh (I need a processor) once I get money to buy a new one I'll be back.

**Comment by Niller303** [comment]
No worries im not in a hurry.
You can get some dirt cheap hackintosh compatible processors like core 2 duo and used modern processors on ebay.

**Comment by Mirone** [comment]
Yes, I find some processors on ebay, but I need
From the money to buy it and still have not, this money. :(
