### ISSUE TITLE
Support for Realtek ALC294 10.12.6

### ISSUE THREAD

**Issue by starcentral** [Mirone/AppleHDAPatcher#14]
Is it possible to get AppleHDA patcher to support realtek ALC294?

**Comment by Mirone** [comment]
Of course, I just need a codec_dump.

**Comment by starcentral** [comment]
wow thanks for the support !!! this ALC294 is killing me!  :/

**Comment by starcentral** [comment]
WOW thanks for the support. This ALC294 is killing me ! 

www.hy-way.com/alc294/codec_dump.txt

**Comment by starcentral** [comment]
WOW thanks for your SPEED!! I'm bit of noob with all this stuff, the patch needs HDEF but there is no HDEF branch anywhere in my DSDT  ->   www.hy-way.com/alc294/DSDT.dsl

**Comment by Mirone** [comment]
Send me your clover folder.
Tell me the specifications of your Hardware.

**Comment by starcentral** [comment]
ASUS laptop UX430UAR, i7 8550, Intel 620, ALC294. wifi card not replaced yet with broadcom. I only have 4 patches I made to virgin DSDT to get trackpad working via voodooI2C and keyboard backlight.

 www.hy-way.com/alc294/CLOVER.zip

**Comment by Mirone** [comment]
try this: 
[CLOVER.zip](https://github.com/Mirone/AppleHDAPatcher/files/1693341/CLOVER.zip)

repair permissions rebuild caches after install AppleHDA.

**Comment by starcentral** [comment]
Thank you, it did not work. I think config.plist is missing the required patches for the AppleHDA binary?

**Comment by Mirone** [comment]
send me your IOREG after install the kext.

**Comment by starcentral** [comment]
Is this what you need? 

http://www.hy-way.com/alc294/Screen%20Shot%202018-02-06%20at%205.57.31%20PM.png

**Comment by starcentral** [comment]
http://www.hy-way.com/alc294/sierraiMac.ioreg

![Image of Yaktocat](https://www.hy-way.com/alc294/Screen%20Shot%202018-02-06%20at%205.57.31%20PM.png.png)

**Comment by starcentral** [comment]
http://www.hy-way.com/alc294/sierraiMac.ioreg

**Comment by Mirone** [comment]
try this: 
[AppleHDA-279.48-ALC294.zip](https://github.com/Mirone/AppleHDAPatcher/files/1701201/AppleHDA-279.48-ALC294.zip)

**Comment by starcentral** [comment]
Still doesn't work.

I have layout_id=3 in my config.plist, I use kextbeast to install your AppleHDA.kext to S/L/E.  I did not have HDEF in my DSDT, so I changed your patch to and replaced HDEF with HDAS, is that incorrect procedure? I also have rename HDAS to HDEF in my config.plist.

Here is my ioreg & clover folder:
http://www.hy-way.com/alc294/1/Archive.zip

Thanks for your assistance!

**Comment by Mirone** [comment]
do not use KextBeast, simply copy and paste the kext into S / L / E and then use InsanelyRepairPermissions
http://www.insanelymac.com/forum/files/file/432-insanelyrepairpermission/

**Comment by Mirone** [comment]
working?

**Comment by starcentral** [comment]
hi, thanks for the follow up. Still nothing working for me. I am reading forums a lot, don't I need patched/edited  aDummyHDA.kext and also layout-id and IRQ patch for ACPI? Also I read a lot layout pins config using xml, etc.. I don't know much about this. So far you only provided patched AppleHDA and HDEF patch for ACPI. Let me know, thanks.

Thanks for your assistance !

**Comment by Mirone** [comment]
try this: [Files.zip](https://github.com/Mirone/AppleHDAPatcher/files/1722059/Files.zip)
replace your clover folder(don't forget a make backup the current folder before) with attached,
install AppleHDA+codec_commander in: S/L/E, rebuild caches and repair permissions.

**Comment by starcentral** [comment]
I've installed AppleHDA + codec_commander in S/L/E and used your config.plist and patched files, still no devices shown under system preferences -> sound -> output.  cheers thanks!

[debug_31506.zip](https://github.com/Mirone/AppleHDAPatcher/files/1733298/debug_31506.zip)

**Comment by starcentral** [comment]
sorry I accidentally closed this post. I've reopened. 

I've installed the AppleHDA + codec_commander in S/L/E and also installed the edited Lilu.kext and IntelGraphicsFix kexts you sent back to L/E. Rebuilt cache. I switched to a different config.plist since you had edited mine, so I matched the same parameters you changed in mine and put them in my new config.plist which was:  disable rename HDAS->HDEF, audio inject set from 3 to "no",  Inject Keys "yes".

After reboot there are no devices shown under system preferences -> sound -> output.

Under IOreg I see HDEF and under layout-ID it says 00 00 00 00.  I should have something there shouldn't I? I see pin layout in AppleHDA.kext ->info.plist  says layout-id 8. I am not expert at any of this.

Thanks again for any help!

[debug_9849.zip](https://github.com/Mirone/AppleHDAPatcher/files/1733754/debug_9849.zip)

**Comment by Mirone** [comment]
I'm going to send you a config.plist and I want you to use it, yours seems to be a bit messy.

**Comment by Mirone** [comment]
use this: [config.plist.zip](https://github.com/Mirone/AppleHDAPatcher/files/1733781/config.plist.zip)With what tool are you repairing permissions and rebuilding caches?

**Comment by starcentral** [comment]
Hm, the config.plist shouldn't be too messy - it is basically stock https://github.com/RehabMan/OS-X-Clover-Laptop-Config/blob/master/config_HD615_620_630_640_650.plist for better IntelGFX & ig-platform-id settings for my machine. Then I add change F%uT%04x to F%uTxxxx in AppleBacklightInjector.kext (credit RehabMan)” and enable change _DSM to XDSM for a final graphics fixes.

**Comment by Mirone** [comment]
I understand, but in my view RehabMan, provides an example of config.plist
and the same should be changed according to your need.
another thing why you need 10.12.6 would not it be better to use 10.13.x?

**Comment by Mirone** [comment]
> use kextbeast to install to SLE or LE, and then rebuild cache with: sudo touch /Library/Extensions && sudo kextcache -u /. I had no problems installing other kexts so far etc... ?

Only this is not enough to repair the permissions, use this: [RepairPermissions.zip](https://github.com/Mirone/AppleHDAPatcher/files/1733797/RepairPermissions.zip)

copy RepairPermissions folder for your Desktop, open folder and two clicks in RepairPermissions.command

**Comment by starcentral** [comment]
Ok I put your new config.plist in my clover folder, made sure kexts were installed to SLE, rebuild cache and ran repairPermission.  Still no devices listed under sound devices. IOReg shows layout-id 3, maybe good sign. How do we know which layout ID I should be using ?  cheers thanks for help.

**Comment by Mirone** [comment]
try this: 
[AppleHDA-279.48-ALC294_v1.zip](https://github.com/Mirone/AppleHDAPatcher/files/1734013/AppleHDA-279.48-ALC294_v1.zip)
[Uploading AppleHDA-279.48-ALC294_v2.zip…]()

**Comment by starcentral** [comment]
the v2 link does not work.

I installed AppleHDA from the v1 link. Did I need to apply the DSDT patch (see below) that is in the readme.rtf? I tried it both ways anyway, and neither gave me devices under sound list.  I can confirm I am still using the DSDT.aml you provided 4 days ago via https://github.com/Mirone/AppleHDAPatcher/files/1722059/Files.zip


```
into method label _DSM parent_label HDEF remove_entry;
into device label HDEF insert
begin
Method (_DSM, 4, NotSerialized)\n
{\n
    If (LEqual (Arg2, Zero)) { Return (Buffer() { 0x03 } ) }\n
    Return (Package()\n
    {\n
        "built-in", Buffer() { 0x00 },\n
        "layout-id", Buffer() { 0x03, 0x00, 0x00, 0x00 },\n
        "hda-gfx", Buffer() { "onboard-1" },\n
        "PinConfigurations", Buffer() { },\n
    })\n
}\n
end;
```

thanks again for your time!

**Comment by Mirone** [comment]
Ok, I Think that we are giving punches to the wall here, let tell me which method of installation you used to install Sierra?
Why your do not install the High Sierra?

**Comment by Mirone** [comment]
>Did I need to apply the DSDT patch (see below) that is in the readme.rtf?

Not if you inject Layout_id through Clover.

**Comment by starcentral** [comment]
I think we are close. Can it possibly be a different layout_id ?  Where can I read about patching my IRQ's?  I definitely have not done this.

My installation of 12.10.6 was from USB I created using UniBeast. The installation went very smooth and easy, I only applied a few patches to DSDT to get keyboard backlights to work, and screen brightness control.

**Comment by Mirone** [comment]
I suggest a clean installation, without using any method of TonyMac.
