### ISSUE TITLE
Support for ALC230

### ISSUE THREAD

**Issue by damneq** [Mirone/AppleHDAPatcher#15]
Hi, is it possible to add support for Realtek ALC230?
Here is the codec_dump: https://1drv.ms/t/s!AuIoHo29E-jL0Hafz7PHg1smmS8I

**Comment by Mirone** [comment]
Run RunMe.App and send me the generated file on your Desktop.
[RunMe.zip](https://github.com/Mirone/AppleHDAPatcher/files/1714489/RunMe.zip)

**Comment by damneq** [comment]
Here you go
[Send me Damians-MacBook-Pro.zip](https://github.com/Mirone/AppleHDAPatcher/files/1714624/Send.me.Damians-MacBook-Pro.zip)

**Comment by Mirone** [comment]
try this: [AppleHDA-279.48-ALC230.zip](https://github.com/Mirone/AppleHDAPatcher/files/1714672/AppleHDA-279.48-ALC230.zip)
inject Layout_id=3 in your config.plist or DSDT.aml
repair permissions and rebuild caches after install kext.

**Comment by damneq** [comment]
Is it working on High Sierra?

**Comment by Mirone** [comment]
Yeah, 10.13.3

**Comment by damneq** [comment]
Thank you so much! Speakers and headphones are working! You're awesome!

**Comment by damneq** [comment]
But I noticed that after plugging in headphones sound is kinda metallic

**Comment by Mirone** [comment]
try this: [FILES.zip](https://github.com/Mirone/AppleHDAPatcher/files/1714710/FILES.zip)

replace your clover folder(don't forget a make backup the current folder  before) with attached,
install AppleHDA+codec_commander in: S/L/E, rebuild caches and repair permissions.
test all outputs and inputs.

**Comment by damneq** [comment]
Now I'm stuck on loading screen

**Comment by Mirone** [comment]
On the clover boot screen go to Options / ACPI
change DSDT.aml to BIOS.aml

**Comment by damneq** [comment]
Nope

**Comment by Mirone** [comment]
did not work?
Could you send me a picture in verbose mode?

**Comment by damneq** [comment]
First I do this ![](https://i.imgur.com/jLFgic8.jpg)

**Comment by damneq** [comment]
Then I get this![](https://i.imgur.com/jboQulu.jpg)

**Comment by damneq** [comment]
Next I have black screen

**Comment by Mirone** [comment]
This is a problem with the nvidia graphics, you will have to revert your clover folder to the previous one, use a pendrive  if you need to.

**Comment by damneq** [comment]
Yeah, I have disabled my Nvidia with a DSDT patch

**Comment by Mirone** [comment]
create a bootable clover pendrive using your previous files and boot the system.

**Comment by damneq** [comment]
Ok

**Comment by damneq** [comment]
I booted with my previous Clover folder and it's already on my EFI partition

**Comment by Mirone** [comment]
ok, now install only the kehts AppleHDA + codeccommander

**Comment by damneq** [comment]
Now everything seems to be working fine... Bro you're a magician

**Comment by Mirone** [comment]
Enjoy, and do not forget if you can contribute donations are welcome.

P.s: mic's working?

**Comment by damneq** [comment]
Input level is showing in System Preferences -> Sound so probably yes

**Comment by damneq** [comment]
I'll for sure donate you when I'll get some money (I'm in Middle School)

**Comment by Mirone** [comment]
Do not worry, do it when you can.
test, comboJack, use iPhone Headset.

**Comment by damneq** [comment]
Uhh... I don't have any devices using comboJack, sorry

**Comment by Mirone** [comment]
no problem, please send me a copy of your IOREG after install the kexts

**Comment by damneq** [comment]
Thanks again
[Damians-MacBook-Pro.ioreg.zip](https://github.com/Mirone/AppleHDAPatcher/files/1714775/Damians-MacBook-Pro.ioreg.zip)

**Comment by Mirone** [comment]
thanks,
enjoy the good sound!
