### ISSUE TITLE
request help alc294

### ISSUE THREAD

**Issue by mxrkd** [Mirone/AppleHDAPatcher#20]
Guide for what?
AppleHDA?

And please, do not hijack a thread. If you need help, create a new thread instead. Thanks

_Originally posted by @Striker770 in https://github.com/Mirone/AppleHDAPatcher/issues/19#issuecomment-439855440_

**Comment by Striker770** [comment]
> Guide for what?
> AppleHDA?
> 
> And please, do not hijack a thread. If you need help, create a new thread instead. Thanks
> 
> _Originally posted by @Striker770 in [#19 (comment)](https://github.com/Mirone/AppleHDAPatcher/issues/19#issuecomment-439855440)_

Do you need help for ALC294?
If yes, what's the hardware?
What's the macOS version installed?

**Comment by mxrkd** [comment]
Sorry for my English. I have no experience in installing hackintosh, but I managed to run it on my asus ZenBook ux430unr (kaby lake r). I was guided by the instructions on [GitHub](https://github.com/hieplpvip/ASUS-ZENBOOK-HACKINTOSH)
i7-8550u
intel hd620
nvidia mx150 (turn off)
I have no sound in headphones
Installed macOS 10.14

**Comment by Striker770** [comment]
> i7-8550u

Okay. No problem.
That's good
Did you tried the Mirone AppleHDA?

Post your Clover folder

**Comment by mxrkd** [comment]
> Did you tried the Mirone AppleHDA?
No i don't. And i don't know how
[CLOVER.zip](https://github.com/Mirone/AppleHDAPatcher/files/2595133/CLOVER.zip)

**Comment by Striker770** [comment]
The AppleHDA should always be installed to S/L/E otherwise it won't load.

**Comment by mxrkd** [comment]
> The AppleHDA should always be installed to S/L/E otherwise it won't load.

I set it to S/L/E. So what's next?

**Comment by Striker770** [comment]
> > The AppleHDA should always be installed to S/L/E otherwise it won't load.
> 
> I set it to S/L/E. So what's next?

Attach a screenshot of DPCI Manager>Status

**Comment by Striker770** [comment]
> > I set it to S/L/E. So what's next?
> 
> i need reboot after it?

Nothing. It was just a general thing. Will post your updated Clover folder in a while.

**Comment by mxrkd** [comment]
![2018-11-19 15 05 04](https://user-images.githubusercontent.com/45165251/48706182-89c5bb80-ec0c-11e8-8f36-a5bbc5a72df2.png)
> Attach a screenshot of DPCI Manager>Status

**Comment by Striker770** [comment]
> ![2018-11-19 15 05 04](https://user-images.githubusercontent.com/45165251/48706182-89c5bb80-ec0c-11e8-8f36-a5bbc5a72df2.png)
> 
> > Attach a screenshot of DPCI Manager>Status

Also, the PCI List Tab

**Comment by mxrkd** [comment]
![2018-11-19 15 07 50](https://user-images.githubusercontent.com/45165251/48706300-e45f1780-ec0c-11e8-875e-4686e670a608.png)

**Comment by Striker770** [comment]
You've many unnecessary kexts installed.

**Comment by mxrkd** [comment]
>I have no experience in installing hackintosh 😁

**Comment by mxrkd** [comment]
what need to do next?

**Comment by Striker770** [comment]
> what need to do next?

Wait. It's morning here. I need to get ready first. Will take some time.

**Comment by mxrkd** [comment]
I think i do something wrong. I deleted my folder CLOVER in EFI/ partition, and place your CLOVER folder. Replace AppleHDA in S/L/E, after it i check S/L/E and L/E folders for deleting AppleALC and VoodooHDA, but they were not. After i extract CodecManager.kext to EFI/CLOVER/kexts/Other and S/L/E. After all steps in guide, i reboot my computer, and the sound disappeared completely

**Comment by Striker770** [comment]
> I think i do something wrong. I deleted my folder CLOVER in EFI/ partition, and place your CLOVER folder. Replace AppleHDA in S/L/E, after it i check S/L/E and L/E folders for deleting AppleALC and VoodooHDA, but they were not. After i extract CodecManager.kext to EFI/CLOVER/kexts/Other and S/L/E. After all steps in guide, i reboot my computer, and the sound disappeared completely

Okay.
Post your EFI+IOReg

**Comment by mxrkd** [comment]
[EFI.zip](https://github.com/Mirone/AppleHDAPatcher/files/2595596/EFI.zip)

[IOReg.zip](https://github.com/Mirone/AppleHDAPatcher/files/2595600/IOReg.zip)

**Comment by mxrkd** [comment]
i deleting my old Clover folder, copy your Clover to /EFI/. Restart and laptop can't loading after logo apple. I booted from a usb flash

**Comment by Striker770** [comment]
> i deleting my old Clover folder, copy your Clover to /EFI/. Restart and laptop can't loading after logo apple. I booted from a usb flash

Okay. I would need the boot logs. Attach a photo of verbose.

**Comment by mxrkd** [comment]
Sorry for so long. It's it?
![img_0960](https://user-images.githubusercontent.com/45165251/48716752-0f576480-ec29-11e8-9453-5c55e587166d.png)

**Comment by mxrkd** [comment]
After that, the screen turns black and does not boot. However, if you click on the caps lock, the indicator will switch.

**Comment by Striker770** [comment]
> After that, the screen turns black and does not boot. However, if you click on the caps lock, the indicator will switch.

Okay. Use this.
Remove old EFI
Replace with this one 
[EFI.zip](https://github.com/Mirone/AppleHDAPatcher/files/2595949/EFI.zip)
Report

**Comment by mxrkd** [comment]
Now system is load but still no sound
![2018-11-19 18 54 01](https://user-images.githubusercontent.com/45165251/48718460-7c202e00-ec2c-11e8-8b57-5cf12927b9f3.png)
![2018-11-19 18 54 16](https://user-images.githubusercontent.com/45165251/48718474-8510ff80-ec2c-11e8-8c64-aa80d2bc4f94.png)

**Comment by Striker770** [comment]
Provide IOReg

**Comment by mxrkd** [comment]
[IOReg2.zip](https://github.com/Mirone/AppleHDAPatcher/files/2596037/IOReg2.zip)

**Comment by Striker770** [comment]
Run this command in terminal
sudo kextcache -i/
Provide output

**Comment by mxrkd** [comment]
Last login: Mon Nov 19 18:52:53 on ttys000
MacBook-Pro:~ mark$ sudo kextcache -i/
Password:
Sorry, try again.
Password:
Kext with invalid signatured (-67062) allowed: <OSKext 0x7fd82d832310 [0x7fff9dc878e0]> { URL = "CodecCommander.kext/ -- file:///Library/Extensions/", ID = "org.tw.CodecCommander" }
KernelCache ID: E75E0DC768871B32DBBAA6A124EA6061
Kext rejected due to improper filesystem permissions: <OSKext 0x7f8589621320 [0x7fff9dc878e0]> { URL = "AppleHDA.kext/ -- file:///System/Library/Extensions/", ID = "com.apple.driver.AppleHDA" }
Kext rejected due to improper filesystem permissions: <OSKext 0x7f8589635db0 [0x7fff9dc878e0]> { URL = "IOHDAFamily.kext/ -- file:///System/Library/Extensions/AppleHDA.kext/Contents/PlugIns/", ID = "com.apple.iokit.IOHDAFamily" }
Kext rejected due to improper filesystem permissions: <OSKext 0x7f8589643900 [0x7fff9dc878e0]> { URL = "AppleMikeyDriver.kext/ -- file:///System/Library/Extensions/AppleHDA.kext/Contents/PlugIns/", ID = "com.apple.driver.AppleMikeyDriver" }
Kext rejected due to improper filesystem permissions: <OSKext 0x7f8589658b40 [0x7fff9dc878e0]> { URL = "AppleHDAHardwareConfigDriver.kext/ -- file:///System/Library/Extensions/AppleHDA.kext/Contents/PlugIns/", ID = "com.apple.driver.AppleHDAHardwareConfigDriver" }
Kext rejected due to improper filesystem permissions: <OSKext 0x7f85896057f0 [0x7fff9dc878e0]> { URL = "DspFuncLib.kext/ -- file:///System/Library/Extensions/AppleHDA.kext/Contents/PlugIns/", ID = "com.apple.driver.DspFuncLib" }
Kext rejected due to improper filesystem permissions: <OSKext 0x7f858962a8a0 [0x7fff9dc878e0]> { URL = "AppleHDAController.kext/ -- file:///System/Library/Extensions/AppleHDA.kext/Contents/PlugIns/", ID = "com.apple.driver.AppleHDAController" }
Kext with invalid signatured (-67062) allowed: <OSKext 0x7f858985a3a0 [0x7fff9dc878e0]> { URL = "CodecCommander.kext/ -- file:///Library/Extensions/", ID = "org.tw.CodecCommander" }
Kext with invalid signatured (-67062) allowed: <OSKext 0x7f85898714f0 [0x7fff9dc878e0]> { URL = "X86PlatformPluginInjector.kext/ -- file:///Library/Extensions/", ID = "com.apple.driver.X86PlatformPlugin" }
Kext with invalid signatured (-67062) allowed: <OSKext 0x7f85898761a0 [0x7fff9dc878e0]> { URL = "BrcmFirmwareRepo.kext/ -- file:///Library/Extensions/", ID = "com.no-one.BrcmFirmwareStore" }
Kext with invalid signatured (-67062) allowed: <OSKext 0x7f8589879980 [0x7fff9dc878e0]> { URL = "BrcmPatchRAM2.kext/ -- file:///Library/Extensions/", ID = "com.no-one.BrcmPatchRAM2" }

**Comment by Striker770** [comment]
> Last login: Mon Nov 19 18:52:53 on ttys000
> MacBook-Pro:~ mark$ sudo kextcache -i/
> Password:
> Sorry, try again.
> Password:
> Kext with invalid signatured (-67062) allowed: <OSKext 0x7fd82d832310 [0x7fff9dc878e0]> { URL = "CodecCommander.kext/ -- file:///Library/Extensions/", ID = "org.tw.CodecCommander" }
> KernelCache ID: E75E0DC768871B32DBBAA6A124EA6061
> Kext rejected due to improper filesystem permissions: <OSKext 0x7f8589621320 [0x7fff9dc878e0]> { URL = "AppleHDA.kext/ -- file:///System/Library/Extensions/", ID = "com.apple.driver.AppleHDA" }
> Kext rejected due to improper filesystem permissions: <OSKext 0x7f8589635db0 [0x7fff9dc878e0]> { URL = "IOHDAFamily.kext/ -- file:///System/Library/Extensions/AppleHDA.kext/Contents/PlugIns/", ID = "com.apple.iokit.IOHDAFamily" }
> Kext rejected due to improper filesystem permissions: <OSKext 0x7f8589643900 [0x7fff9dc878e0]> { URL = "AppleMikeyDriver.kext/ -- file:///System/Library/Extensions/AppleHDA.kext/Contents/PlugIns/", ID = "com.apple.driver.AppleMikeyDriver" }
> Kext rejected due to improper filesystem permissions: <OSKext 0x7f8589658b40 [0x7fff9dc878e0]> { URL = "AppleHDAHardwareConfigDriver.kext/ -- file:///System/Library/Extensions/AppleHDA.kext/Contents/PlugIns/", ID = "com.apple.driver.AppleHDAHardwareConfigDriver" }
> Kext rejected due to improper filesystem permissions: <OSKext 0x7f85896057f0 [0x7fff9dc878e0]> { URL = "DspFuncLib.kext/ -- file:///System/Library/Extensions/AppleHDA.kext/Contents/PlugIns/", ID = "com.apple.driver.DspFuncLib" }
> Kext rejected due to improper filesystem permissions: <OSKext 0x7f858962a8a0 [0x7fff9dc878e0]> { URL = "AppleHDAController.kext/ -- file:///System/Library/Extensions/AppleHDA.kext/Contents/PlugIns/", ID = "com.apple.driver.AppleHDAController" }
> Kext with invalid signatured (-67062) allowed: <OSKext 0x7f858985a3a0 [0x7fff9dc878e0]> { URL = "CodecCommander.kext/ -- file:///Library/Extensions/", ID = "org.tw.CodecCommander" }
> Kext with invalid signatured (-67062) allowed: <OSKext 0x7f85898714f0 [0x7fff9dc878e0]> { URL = "X86PlatformPluginInjector.kext/ -- file:///Library/Extensions/", ID = "com.apple.driver.X86PlatformPlugin" }
> Kext with invalid signatured (-67062) allowed: <OSKext 0x7f85898761a0 [0x7fff9dc878e0]> { URL = "BrcmFirmwareRepo.kext/ -- file:///Library/Extensions/", ID = "com.no-one.BrcmFirmwareStore" }
> Kext with invalid signatured (-67062) allowed: <OSKext 0x7f8589879980 [0x7fff9dc878e0]> { URL = "BrcmPatchRAM2.kext/ -- file:///Library/Extensions/", ID = "com.no-one.BrcmPatchRAM2" }

How did you installed AppleHDA?

**Comment by mxrkd** [comment]
I copied it with a replacement in the folder S/L/E

**Comment by Striker770** [comment]
> I copied it with a replacement in the folder S/L/E

WRONG. Read here: https://www.elitemacx86.com/threads/guide-installing-kexts.259/
Remove AppleHDA from S/L/E
Install it using KextUtility. Terminal maybe issue for you.

**Comment by mxrkd** [comment]
i have backup original AppleHDA from S/L/E

**Comment by Striker770** [comment]
> i have backup original AppleHDA from S/L/E

YOU DO NOT NEED TO INSTALL THE ORIGINAL AppleHDA. Use the AppleHDA which i provided you.
I'm linking it again. https://github.com/Mirone/AppleHDAPatcher/files/2595417/AppleHDA-281.52-ALC294.zip

**Comment by mxrkd** [comment]
O MY GOD ITS WORK. I understood correctly, every time when I insert my headphones, do I need to run "Jack fix"?

**Comment by Striker770** [comment]
> O MY GOD ITS WORK. I understood correctly, every time when I insert my headphones, do I need to run "Jack fix"?

Enjoy the good Sound. All credit goes to Mirone and to the great forum. 
Yes, no other option. If you want to donate, you can.
:)

**Comment by Mirone** [comment]
> > i have backup original AppleHDA from S/L/E
> 
> YOU DO NOT NEED TO INSTALL THE ORIGINAL AppleHDA. Use the AppleHDA which i provided you.

The same AppleHDA that I have fixed for you worked for it?

**Comment by mxrkd** [comment]
thank you guys

**Comment by Striker770** [comment]
> > > i have backup original AppleHDA from S/L/E
> > 
> > 
> > YOU DO NOT NEED TO INSTALL THE ORIGINAL AppleHDA. Use the AppleHDA which i provided you.
> 
> The same AppleHDA that I have fixed for you worked for it?

Yes, my dear. He's running many unnecessary things but we needed to make the Audio working and it's working now.
Kudos to you @Mirone

**Comment by mxrkd** [comment]
>He's running many unnecessary things

What are you talking about? What is worth getting rid of?

**Comment by mxrkd** [comment]
I am going to buy DW1560

>x86platform is modified

I'm sorry I did not understand

>ENGLISH ONLY

missclick

**Comment by Striker770** [comment]
> I am going to buy DW1560
> 
> > x86platform is modified
> 
> I'm sorry I did not understand
> 
> > ENGLISH ONLY
> 
> missclick

When you buy, install the kexts. No need until you have the hardware. X86PlatformPluginInjector.kext should be removed from S/L/E

**Comment by mxrkd** [comment]
in S/L/E i don't have X86PlatformPluginInjector.kext 
but in L/E its it
![screenshot 2018-11-19 at 19 38 08](https://user-images.githubusercontent.com/45165251/48721412-ecca4900-ec32-11e8-91fa-d512e2f47fdb.png)
![screenshot 2018-11-19 at 19 40 15](https://user-images.githubusercontent.com/45165251/48721474-0ec3cb80-ec33-11e8-992f-6db17b7eaeec.png)
Remove it from L/E?

**Comment by Striker770** [comment]
> in S/L/E i don't have X86PlatformPluginInjector.kext
> but in L/E its it
> ![screenshot 2018-11-19 at 19 38 08](https://user-images.githubusercontent.com/45165251/48721412-ecca4900-ec32-11e8-91fa-d512e2f47fdb.png)
> ![screenshot 2018-11-19 at 19 40 15](https://user-images.githubusercontent.com/45165251/48721474-0ec3cb80-ec33-11e8-992f-6db17b7eaeec.png)
> Remove it from L/E?

YES

**Comment by Striker770** [comment]
Restart, provide IOReg.

**Comment by mxrkd** [comment]
[IOReg4.zip](https://github.com/Mirone/AppleHDAPatcher/files/2596227/IOReg4.zip)

**Comment by Striker770** [comment]
> [IOReg4.zip](https://github.com/Mirone/AppleHDAPatcher/files/2596227/IOReg4.zip)

Your CPU PM is working now. Follow this guide and provide Output: https://www.elitemacx86.com/threads/guide-how-to-generate-ssdt-for-cpu-power-management.96/
And why don't you join the forum?
Would be too easy for me.

**Comment by mxrkd** [comment]
> And why don't you join the forum?

ok, i will register

**Comment by Striker770** [comment]
> > And why don't you join the forum?
> 
> ok, i will register

It would be easy for me to help from there.

**Comment by Mirone** [comment]
Guys let's just keep discussion about AppleHDA here.

**Comment by Striker770** [comment]
> Guys let's just keep discussion about AppleHDA here.

For sure. As you already see, the Audio is working. And the CPU PM works now.
No harm to anyone. We're in a community and we should support each other.

**Comment by Mirone** [comment]
> > Guys let's just keep discussion about AppleHDA here.
> 
> For sure. As you already see, the Audio is working. And the CPU PM works now.
> No harm to anyone. We're in a community and we should support each other.

Yes, no harm, but here it will be discussed only about AppleHDA since the purpose here is this, if you want help about something else you will be very welcome on olarila.com.

**Comment by Striker770** [comment]
> > > Guys let's just keep discussion about AppleHDA here.
> > 
> > 
> > For sure. As you already see, the Audio is working. And the CPU PM works now.
> > No harm to anyone. We're in a community and we should support each other.
> 
> Yes, no harm, but here it will be discussed only about AppleHDA since the purpose here is this, if you want help about something else you will be very welcome on olarila.com.

Yes.

**Comment by Mirone** [comment]
do not misunderstand, it's just to keep things in their proper place.

**Comment by Striker770** [comment]
> do not misunderstand, it's just to keep things in their proper place.

I agree, as the Audio was fixed and the other issue remains which is not related to AppleHDA, so i asked him to join the forum so that other issues can be fixed too.

**Comment by Mirone** [comment]
thank you for your understanding!

**Comment by Striker770** [comment]
> thank you for your understanding!
You're most welcome. I would be leaving soon for some work and recharging my CC today. Hehe
If you want, i can continue discussion with him here with the other issues.

**Comment by Mirone** [comment]
I think Audio and power management is already good size, a little research is good for learning.

**Comment by Striker770** [comment]
> I think Audio and power management is already good size, a little research is good for learning.

Cool!

**Comment by Striker770** [comment]
@mxrkd I'm waiting for your Output

**Comment by Mirone** [comment]
I will close this Issue and give it as solved, in the future the author will be able to reopen it if it deems it necessary.
