### ISSUE TITLE
AppleHDa do not work after update successfully macOS Sierra ?

### ISSUE THREAD

**Issue by cvulam** [Mirone/AppleHDAPatcher#3]
Hi Miron !
I use patch appleHDA of you on mac os EL Capitan it work perfect, but after update macOS Sierra i use kext for the new version it do not work, then had patch again it do not work.do not know when you will update the new version support macOS 10.12. Thank you very much !

**Comment by Mirone** [comment]
What is your codec? 
could send me a copy of your IOREG?

**Comment by cvulam** [comment]
My codec Realtek ALC 255.
IOREG : IOREG 10.11.6 has patch and IOREG 10.12 not yet patch.
[Lâm’s MacBook Pro 10.11.6.ioreg.zip](https://github.com/Mirone/AppleHDAPatcher/files/491041/Lam.s.MacBook.Pro.10.11.6.ioreg.zip)
[Lâm’s MacBook Pro 10.12.ioreg.zip](https://github.com/Mirone/AppleHDAPatcher/files/491042/Lam.s.MacBook.Pro.10.12.ioreg.zip)

**Comment by Mirone** [comment]
After installing AppleHDA repair permissions using
this tool: http://www.insanelymac.com/forum/files/file/432-insanelyrepairpermission/

after run this commands in terminal:
sudo touch /S*/L*/Extensions
sudo kextcache -Boot -U /
