### ISSUE TITLE
Laptop with CX20590

### ISSUE THREAD

**Issue by rubel-ahammad** [Mirone/AppleHDAPatcher#8]
Do you have any plan add support for this device? Please let me know if I can help you in this regard?

**Comment by Mirone** [comment]
I need your codec_dump.

**Comment by rubel-ahammad** [comment]
[codec_dump.txt](https://github.com/Mirone/AppleHDAPatcher/files/936018/codec_dump.txt)

**Comment by Mirone** [comment]
@rubel-ahammad , 
Your dump codec
Says if it is a CX20590, so this codec is supported by AppleHDA Patcher.

**Comment by rubel-ahammad** [comment]
I have executed following steps. But audio is not working yet.
1. Download and run your app.
2. Dragged the folder CX20590 onto the app. This created a zip on my Desktop.
3. Extracted the zip and installed the kext using Kext Wizard. Repaired permissions and the Reboot.

Please suggest if I am missing something.

**Comment by Mirone** [comment]
@rubel-ahammad  send me your config.plist+DSDT.

**Comment by rubel-ahammad** [comment]
Hi @Mirone,

Sorry for late reply. Please find the config and DSDT.aml in the zip attached.

[config+DSDT.zip](https://github.com/Mirone/AppleHDAPatcher/files/948918/config.DSDT.zip)

**Comment by rubel-ahammad** [comment]
Hello @Mirone ,

Eagerly waiting for your response.
